### ISSUE TITLE
HsOpenSSL fails to build with GHC 9.12 due to Setup.hs

### ISSUE THREAD

**Issue by sternenseemann** [haskell-cryptography/HsOpenSSL#99]
```
[1 of 2] Compiling Main             ( Setup.hs, /build/tmp.Tt5zAR40li/Main.o )
Setup.hs:75:44: error: [GHC-16444]
    • non-bidirectional pattern synonym ‘ConfigCommonFlags’ used in an expression
    • In a record update at field ‘configVerbosity’
      and with pattern synonym ‘ConfigCommonFlags’.
      In the second argument of ‘setFlag’, namely
        ‘cfg {configVerbosity = toFlag silent}’
      In the second argument of ‘($)’, namely
        ‘setFlag (mkFlagName f) cfg {configVerbosity = toFlag silent}’
   |
75 |                     setFlag (mkFlagName f) cfg { configVerbosity = toFlag silent }
   |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by vshabanov** [comment]
I will gladly accept the patch that fixes this.

**Comment by andreasabel** [comment]
I revised the published versions with the `Cabal < 3.14` bound:


2024-12-31T10:16:13Z  	AndreasAbel	  [HsOpenSSL-0.11.7-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.7/revisions)
2024-12-31T10:16:13Z  	AndreasAbel	  [HsOpenSSL-0.11.7.8-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.7.8/revisions)
2024-12-31T10:16:13Z  	AndreasAbel	  [HsOpenSSL-0.11.7.7-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.7.7/revisions)
2024-12-31T10:16:12Z  	AndreasAbel	  [HsOpenSSL-0.11.7.6-r2](https://hackage.haskell.org/package/HsOpenSSL-0.11.7.6/revisions)
2024-12-31T10:16:12Z  	AndreasAbel	  [HsOpenSSL-0.11.7.5-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.7.5/revisions)
2024-12-31T10:16:12Z  	AndreasAbel	  [HsOpenSSL-0.11.7.4-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.7.4/revisions)
2024-12-31T10:16:12Z  	AndreasAbel	  [HsOpenSSL-0.11.7.3-r2](https://hackage.haskell.org/package/HsOpenSSL-0.11.7.3/revisions)
2024-12-31T10:16:11Z  	AndreasAbel	  [HsOpenSSL-0.11.7.2-r4](https://hackage.haskell.org/package/HsOpenSSL-0.11.7.2/revisions)
2024-12-31T10:16:11Z  	AndreasAbel	  [HsOpenSSL-0.11.7.1-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.7.1/revisions)
2024-12-31T10:16:11Z  	AndreasAbel	  [HsOpenSSL-0.11.6-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.6/revisions)
2024-12-31T10:16:11Z  	AndreasAbel	  [HsOpenSSL-0.11.6.2-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.6.2/revisions)
2024-12-31T10:16:11Z  	AndreasAbel	  [HsOpenSSL-0.11.6.1-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.6.1/revisions)
2024-12-31T10:16:10Z  	AndreasAbel	  [HsOpenSSL-0.11.5-r2](https://hackage.haskell.org/package/HsOpenSSL-0.11.5/revisions)
2024-12-31T10:16:10Z  	AndreasAbel	  [HsOpenSSL-0.11.5.1-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.5.1/revisions)
2024-12-31T10:16:08Z  	AndreasAbel	  [HsOpenSSL-0.11.4.20-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.4.20/revisions)
2024-12-31T10:16:07Z  	AndreasAbel	  [HsOpenSSL-0.11.4.19-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.4.19/revisions)
2024-12-31T10:16:07Z  	AndreasAbel	  [HsOpenSSL-0.11.4.18-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.4.18/revisions)
2024-12-31T10:16:07Z  	AndreasAbel	  [HsOpenSSL-0.11.4.17-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.4.17/revisions)
2024-12-31T10:16:07Z  	AndreasAbel	  [HsOpenSSL-0.11.4.16-r3](https://hackage.haskell.org/package/HsOpenSSL-0.11.4.16/revisions)
2024-12-31T10:16:07Z  	AndreasAbel	  [HsOpenSSL-0.11.4.15-r2](https://hackage.haskell.org/package/HsOpenSSL-0.11.4.15/revisions)
2024-12-31T10:16:06Z  	AndreasAbel	  [HsOpenSSL-0.11.4.14-r2](https://hackage.haskell.org/package/HsOpenSSL-0.11.4.14/revisions)
2024-12-31T10:16:06Z  	AndreasAbel	  [HsOpenSSL-0.11.4.13-r1](https://hackage.haskell.org/package/HsOpenSSL-0.11.4.13/revisions)

**Comment by andreasabel** [comment]
It seems like `Setup.hs` does not actually influence the installation, it only provides advice to mac users how to install the system libraries.  This could as well be restricted to the README.

If my assumption about `Setup.hs` is correct, I suggest to simply remove it and use `build-type: Simple` instead.

Custom setups easily break with `Cabal` updates and the cabal developers are discouraging custom setups, looking for a new, more declarative model.

If you agree @vshabanov , I can submit a PR to that extend.

**Comment by andreasabel** [comment]
CC @Kleidukos maybe you have an opinion on this...

**Comment by Kleidukos** [comment]
In favour of removing the Custom build type, which can be replaced with the new Hooks build type when it gets sufficiently adopted, **if needed**. :)

**Comment by vshabanov** [comment]
Yes, it's fine to remove it.

IIRC, I added the automatic configuration not to break macOS builds as it wasn't easy to specify package flags back in the day. It's very easy to do now by adding `cabal.project.local` with
```
package HsOpenSSL
  flags: +use-pkg-config
-- or +macports-openssl
-- or +homebrew-openssl
```
so I hope that the lack of the auto-configuration won't be a big issue.
